version: '3'

volumes:
  store:
    driver: local
  bundle:
    driver: local

services:
  mysql:
    image: staff0rd/mysql-minimal
    ports:
      - 3307:3306
    volumes:
      - store:/var/lib/mysql/data
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
  redis:
    image: redis

  web:
    build: .
    ports:
      - 3000:3000
    volumes:
      - .:/app
      - bundle:/usr/local/bundle
    links:
      - mysql
      - redis
    # Keep the stdin open, so we can attach to our app container's process and do things such as
    # byebug, etc:
    stdin_open: true
    # Enable sending signals (CTRL+C, CTRL+P + CTRL+Q) into the container:
    tty: true
    command: ./bin/start.sh
    environment: &app_env
      RAILS_ENV: development
      PORT: 3000
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: root
      DB_PSWD: root
      DB_NAME: development_database
      DB_ADAPTER: mysql2
      DB_ENCODING: utf8mb4
